# Generated by Django 5.2.1 on 2025-07-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_estudiante_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(default='fotos_estudiantes/default.jpg', upload_to='fotos_estudiantes/'),
        ),
    ]
